# Generated by Django 4.1.5 on 2023-01-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_estudiantes_fechadenaci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='fechaDeNaci',
            field=models.DateField(default='2023-01-23'),
        ),
    ]
